name: Sync Gitee to GitHub

on:
  schedule:
    # 每小时执行一次，除了 3 点到 8 点之间
    - cron: "0 0-2,9-23 * * *"  # 每小时的整点触发，排除 3 到 8 点
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout GitHub repository
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      # Set up Git
      - name: Set up Git
        run: |
          git config --global user.name "mbxj"  # 设置 Git 用户名
          git config --global user.email "838756854@qq.com"  # 设置 Git 邮箱

      # Clone the Gitee repository
      - name: Clone Gitee repository
        run: |
          git clone -b master https://gitee.com/xx68/x6.git  # 克隆 Gitee 仓库的 master 分支
          ls -la x6  # 列出克隆后目录的内容，确保文件被成功下载

      # Copy files from Gitee to GitHub repo
      - name: Copy files to GitHub repository
        run: |
          cp -r x6/* .  # 复制 Gitee 仓库中的所有文件到当前 GitHub 仓库目录
          
      # Commit and push to GitHub
      - name: Commit and push to GitHub
        run: |
          git add .  # 添加所有文件
          git commit -m "Sync files from Gitee repository"  # 提交
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/mbxj/cb.github.io.git main  # 推送到 GitHub 仓库
